- name: Configuration for petclinic AWS project
  hosts: all
  become: yes
  tasks:
   - name: Install Docker
     yum: 
       name: 
         - docker
       state: latest
   - name: Enable Docker CE service at startup
     service:
       name: docker
       state: started
       enabled: true
